export const AGENTCODE_CONFIG = Symbol('AGENTCODE_CONFIG');
export const AGENTCODE_PRISMA_CLIENT = Symbol('AGENTCODE_PRISMA_CLIENT');
export const AGENTCODE_MODULE_OPTIONS = Symbol('AGENTCODE_MODULE_OPTIONS');
